kind = "web"
previewPath = "/"
title = "freetawn.com"
version = "1.0.0"
id = "artifacts/finutility"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19382

[services.development]
run = "pnpm --filter @workspace/finutility run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/finutility", "run", "build" ]
publicDir = "artifacts/finutility/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19382"
BASE_PATH = "/"
